In [3]:
import sympy
import numpy as np
import scipy.linalg

In [4]:
M = sympy.Matrix([[ 1, -2, 3, 5, 14],
[-2, 4, -5, -10, -26],
[ 2, -4, 6, 11, 29],
[-1, 2, -2, -5, -12]])

In [5]:
print(M.rref())

(Matrix([
[1, -2, 0, 0, 3],
[0,  0, 1, 0, 2],
[0,  0, 0, 1, 1],
[0,  0, 0, 0, 0]]), (0, 2, 3))


In [6]:
A = np.array([[ 1, -2, 3],
[ 2, -4, 7],
[-3, 5, -1]])

b = np.array([1, 3, 2])

x = scipy.linalg.solve(A, b)

print(x)

[4. 3. 1.]


# Tentauppgift 5
!['Tentauppgift'](\\assets\\Tenta_uppg_5.png)<br>
Syftet är att bestämma minsta kvadratlösningen med Python på olika sätt:
Bakgrund: I uppgiften har vi ett överbestämt system, eftersom det är tre ekvationer men bara två okända. Sådana ekvationer går sällan att lösa, förutom om alla punkterna ligger på en rad som kan skäras av en och samma linje. Man kan lösa dessa genom att använda "minsta kvadrat metoden". Då multiplicerar man båda sidorna med A-transponat och löser det efterföljande ekvationssystemet.<br>
När man använder inbyggda funktioner för att lösa ekvations system, som np.linalg.solve eller sympy.solve eller scipy.linalg.solve, så måste det vara square matrices, dvs lika många ekvationer som okända.<br>
Överbestämda system kan direkt lösas med tex Scipy.linalg.lstsq funktionen, alternativt direkt med normalekvationen.


Ett linjärt ekvationssystem, där
- A = koefficient matrisen som innehåller alla koefficienter till de okända x'en
- x = kolonnvektor med alla okända x
- y = kolonnvektor med alla konstanter
- Beräkningarna fungerar nedan, men jag har nog benämnt de olika matriserna med lite fel namn osv. Kan göra om när jag har tid.
<h3>

$Ax = y$
</h3><br>

<h3>

$A=\begin{bmatrix}
1 & 1\\
-1 & 2\\
1 & -1
\end{bmatrix}$
</h3>

<h3>

$y = \begin{bmatrix}
1\\
4\\
0
\end{bmatrix}$
</h3>

<h3>

$x=\begin{bmatrix}
x_1\\
x_2
\end{bmatrix}$<br>

Multiplicera båda leden med A-transponat:
<h3>

$A^TAx = A^Ty$
</h3>
Matrismultiplikation A-transponat gånger A, ger oss:<br>
<h3>

$A^TA = \begin{bmatrix}
3 & -2\\
-2 & 6
\end{bmatrix}$
</h3><br>


In [7]:
A = np.array([[1, 1],[-1, 2],[1, -1]])
y = np.array([[1],[4],[0]])
AT_ggr_A = A.T @ A
AT_ggr_A

array([[ 3, -2],
       [-2,  6]])

Matrismultiplikation A-transponat gånger y, ger oss:<br>
<h3>

$A^Ty = \begin{bmatrix}
1 & -1 & 1\\
1 & 2 & -1
\end{bmatrix}
\begin{bmatrix}
1\\
4\\
0
\end{bmatrix} = 
\begin{bmatrix}
-3\\
9
\end{bmatrix}$
</h3>


In [8]:
AT_ggr_y = A.T @ y
AT_ggr_y

array([[-3],
       [ 9]])

<h3>

$Ax = y$
</h3><br>
dvs:
<h3>

$\begin{bmatrix}
3 & -2\\
-2 & 6
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2
\end{bmatrix} =
\begin{bmatrix}
-3\\
9
\end{bmatrix}$
</h3><br>
som man löser som ett vanligt ekvationsssystem, med gauselimination om man gör det för hand:
<h3>

$\begin{bmatrix}
3 & -2 & -3\\
-2 & 6 & 9
\end{bmatrix}$<br>
</h3>

#### Lösning 1, Sympy:
- Sympy är ett bibliotek för symbolisk matematik.

In [9]:
x1, x2 = sympy.symbols('x1 x2')

eq1 = sympy.Eq(3 * x1 -2 * x2, -3)
eq2 = sympy.Eq(-2 * x1 + 6 * x2, 9)

solution = sympy.solve((eq1, eq2), (x1, x2))

print(solution)

{x1: 0, x2: 3/2}


#### Lösning 2, numpy.linalg.solve
Funktionen ska ha två inputs: <br>
- Koefficientmatrisen A, som innehåller koefficienterna till variablerna i ekvationerna.
- Konstantvektorn y, innehåller alla konstanterna (responsvariablerna) som en kolonnvektor, till höger i ekvationssystemet.
- (AT_ggr_A motsvarar 'A' och AT_ggr_y motsvarar 'y')

In [10]:
solution_np = np.linalg.solve(AT_ggr_A, AT_ggr_y)
print(solution_np)

[[0. ]
 [1.5]]


#### Lösning 3, scipy.linalg.solve
- liknande sätt som man gör i numpy

In [11]:
solution_scipy = scipy.linalg.solve(AT_ggr_A, AT_ggr_y)
print(solution_scipy)

[[0. ]
 [1.5]]


Lösning:<br>
![Lösning](\\assets\\Tenta_uppg_5_lösning.png)

#### Lösning 4: från ML kursen exercise 1:
- Hur man löser ett linjärt ekvationssystem genom att utföra matrismultiplikationen direkt, dvs utan att multiplicera båda leden med A-transponat:

- Denna kod definierar en lambda-funktion med namnet regression_fit, som tar två parametrar: X och y. Lambda-funktionen utför en linjär regression och returnerar de beräknade koefficienterna för regressionsmodellen.<br>
Här är en detaljerad förklaring:<br>
- X representerar matrisen av oberoende variabler (features) i linjär regression. Varje rad i X motsvarar en observation, och varje kolumn representerar en oberoende variabel.
- y representerar vektor av beroende variabler (target values).
- X.T är transpose-matrisen av X, vilket byter plats på rader och kolumner.
- X.T @ X är en matrixmultiplikation mellan X.T och X, vilket resulterar i en ny matris.
- np.linalg.pinv(X.T @ X) beräknar den pseudo-inversa (penrose-moore inversa) av .@X.T@X. Pseudo-inversen används eftersom .X.T@X kanske inte är inverterbar i alla situationer, men pseudo-inversen ger en generaliserad lösning.
- @ X.T multiplicerar pseudo-inversen med X.T.
- @ y multiplicerar resultatet med y.
- Så, sammanfattningsvis utför denna lambda-funktion en linjär regression genom att beräkna pseudo-inversen av @X.T@X och sedan multiplicera den med X.T och y. De beräknade koefficienterna som minimerar kvadratiska förlustfunktionen för regressionen returneras som resultat.

In [12]:
A = np.array([[1, 1],[-1, 2],[1, -1]])
y = np.array([[1],[4],[0]])

regression_fit = lambda A, y: np.linalg.pinv(A.T @ A) @ A.T @ y
beta_hat = regression_fit(A, y)
print(beta_hat)

[[-4.4408921e-16]
 [ 1.5000000e+00]]


Lösning 5, Scipy's funktion för att lösa minsta kvadratmetoden direkt, dvs utan att manuellt beräkna A-transponat gånger A osv.
- Compute least-squares solution to equation Ax = b.
- Verkar som att b också kan vara en array, dvs multipelt antal beroende variabler.
- [SciPy Least Squares documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lstsq.html)<br>
- funktionen returnerar minsta kvadrat lösningen som en array (x), residualen (residues) ?

In [13]:
# Solve for x using scipy.linalg.lstsq
A = np.array([[1, 1],[-1, 2],[1, -1]])
y = np.array([[1],[4],[0]])

x, residuals, rank, s = scipy.linalg.lstsq(A, y)

print("Solution:", x)
print("Residuals:", residuals)
print("Rank", rank)
print("s", s)

Solution: [[-7.19506754e-16]
 [ 1.50000000e+00]]
Residuals: [3.5]
Rank 2
s [2.64575131 1.41421356]


#### Gör en egen beräkning av en enkel linjär regression, en minsta kvadrat anpassning till mätvärden x och y:
- x = [0, 2, 2, -1, 5]
- y = [3, 4, 5, 0, 6]<br>
- beta är här en vektor med beta_0 och beta_1, dvs [beta_0, beta_1]
- Här har vi fallet där man måste addera en "etta" i matrisen för att det ska fungera. I ML brukar det kallas att includera 'bias', när man tar med denna ettan.<br>
![bild](assets/least_squares_1.png)


In [17]:
import numpy as np
x = np.array([[1, 0],[1, 2],[1, 2],[1, -1],[1, 5]])
y = np.array([[3],[4],[5],[0],[6]])
xT_ggr_x = x.T @ x
xT_ggr_y = x.T @ y
beta = np.linalg.pinv(xT_ggr_x) @ xT_ggr_y
print(beta)

[[2.1509434 ]
 [0.90566038]]


np.linalg.solve:

In [15]:
solution_np = np.linalg.solve(xT_ggr_x, xT_ggr_y)
print(solution_np)

[[2.1509434 ]
 [0.90566038]]


np.polyfit:

In [18]:
np.polyfit(x=[0,2,2,-1,5], y=[3,4,5,0,6], deg=1)

array([0.90566038, 2.1509434 ])