In [2]:
import sympy
import numpy as np
import scipy.linalg

In [19]:
M = sympy.Matrix([[ 1, -2, 3, 5, 14],
[-2, 4, -5, -10, -26],
[ 2, -4, 6, 11, 29],
[-1, 2, -2, -5, -12]])

In [20]:
print(M.rref())

(Matrix([
[1, -2, 0, 0, 3],
[0,  0, 1, 0, 2],
[0,  0, 0, 1, 1],
[0,  0, 0, 0, 0]]), (0, 2, 3))


In [21]:
A = numpy.array([[ 1, -2, 3],
[ 2, -4, 7],
[-3, 5, -1]])

b = numpy.array([1, 3, 2])

x = scipy.linalg.solve(A, b)

print(x)

[4. 3. 1.]


# Tentauppgift 5
!['Tentauppgift'](\\assets\\Tenta_uppg_5.png)<br>
Syftet är att bestämma minsta kvadratlösningen med numpy, för att förstå hur man gör.

<h3>

$A=\begin{bmatrix}
1 & 1\\
-1 & 2\\
1 & -1
\end{bmatrix}$
</h3>

<h3>

$y = \begin{bmatrix}
1\\
4\\
0
\end{bmatrix}$
</h3>

<h3>

$x=\begin{bmatrix}
x_1\\
x_2
\end{bmatrix}$<br>
samt
<h3>

$Ax = y$
</h3><br>
Multiplicera båda leden med A-transponat:
<h3>

$A^TAx = A^Ty$
</h3>
Matrismultiplikation A-transponat gånger A, ger oss:<br>
<h3>

$A^TA = \begin{bmatrix}
3 & -2\\
-2 & 6
\end{bmatrix}$
</h3><br>


In [17]:
A = np.array([[1, 1],[-1, 2],[1, -1]])
y = np.array([[1],[4],[0]])
AT_ggr_A = A.T @ A
AT_ggr_A

array([[ 3, -2],
       [-2,  6]])

Matrismultiplikation A-transponat gånger y, ger oss:<br>
<h3>

$A^Ty = \begin{bmatrix}
1 & -1 & 1\\
1 & 2 & -1
\end{bmatrix}
\begin{bmatrix}
1\\
4\\
0
\end{bmatrix} = 
\begin{bmatrix}
-3\\
9
\end{bmatrix}$
</h3>


In [18]:
AT_ggr_y = A.T @ y
AT_ggr_y

array([[-3],
       [ 9]])

<h3>

$Ax = y$
</h3><br>
dvs:
<h3>

$\begin{bmatrix}
3 & -2\\
-2 & 6
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2
\end{bmatrix} =
\begin{bmatrix}
-3\\
9
\end{bmatrix}$
</h3><br>
som man löser som ett vanligt ekvationsssystem, med gauselimination om man gör det för hand:
<h3>

$\begin{bmatrix}
3 & -2 & -3\\
-2 & 6 & 9
\end{bmatrix}$<br>
</h3>
I Python löser man ekvationssystemet med Sympy:


In [24]:
x1, x2 = sympy.symbols('x1 x2')

eq1 = sympy.Eq(3 * x1 -2 * x2, -3)
eq2 = sympy.Eq(-2 * x1 + 6 * x2, 9)

solution = sympy.solve((eq1, eq2), (x1, x2))

print(solution)

{x1: 0, x2: 3/2}


Lösning:<br>
![Lösning](\\assets\\Tenta_uppg_5_lösning.png)